jobs:
  rat_check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: rat check
      run: mvn apache-rat:check -B -Pit,release
    timeout-minutes: 60
name: rat check
on:
  repository_dispatch:
    types: trigger-ga___rat_check.yml
