jobs:
  spotbugs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: spotbugs
      run: mvn -B -Pit -DskipTests clean verify spotbugs:spotbugs
    timeout-minutes: 60
name: spot bugs
on:
  repository_dispatch:
    types: trigger-ga___spotbugs.yml
